[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:icecast]
command=/usr/bin/icecast2 -c /etc/icecast2/icecast.xml
autostart=true
autorestart=true
startretries=5
stdout_logfile=/var/log/supervisor/icecast.out.log
stderr_logfile=/var/log/supervisor/icecast.err.log

[program:flask]
command=python app.py
directory=/app
autostart=true
autorestart=true
startretries=5
stdout_logfile=/var/log/supervisor/flask.out.log
stderr_logfile=/var/log/supervisor/flask.err.log
environment=PYTHONUNBUFFERED="1"

[program:streamer]
command=python streamer.py
directory=/app
autostart=true
autorestart=true
startretries=5
startsecs=10
stdout_logfile=/var/log/supervisor/streamer.out.log
stderr_logfile=/var/log/supervisor/streamer.err.log
environment=PYTHONUNBUFFERED="1"

[program:bot]
command=python radio_bot.py
directory=/app
autostart=false  # NON avviare automaticamente su Render
autorestart=true
startretries=3
stdout_logfile=/var/log/supervisor/bot.out.log
stderr_logfile=/var/log/supervisor/bot.err.log
environment=PYTHONUNBUFFERED="1"
